$script = <<-SCRIPT	
	[ ! -L /usr/bin/python ] && ln -s /usr/bin/python3 /usr/bin/python
SCRIPT

Vagrant.configure("2") do |config|
	
	(1..2).each do |i|
		config.vm.define "node#{i}" do |node|
			node.vm.box = "ubuntu/bionic64"
			node.vm.hostname = "node#{i}"
			j = 200 + i
			node.vm.network "private_network", ip: "192.168.56.#{j}"
			
			node.vm.provider "virtualbox" do |nodes|
				nodes.memory = "1024"
			end
			
			node.vm.provision "shell", inline: $script
			
			node.vm.provision :ansible do |ansible|
				ansible.playbook = "playbook.yml"
			end
		end
	end
	
end
