node{
    stage('Running exercise1'){
        sh 'cd home-assignments/0212/session1 && python3 ./exercise1.py'
    }
    stage('Running exercise2'){
        sh 'cd home-assignments/0212/session1 && python3 ./exercise2.py'
    }
}